import { 
  Check, 
  Download, 
  ExternalLink, 
  FileText, 
  FolderOpen, 
  Database, 
  Box,
  Clock
} from "lucide-react";
import { Link } from "react-router";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { getDateTime } from "@/lib/convertDate"; // Assuming this exists based on your prompt

interface ReceiptModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  header: string;
  description: string;
  itemName: string; // The name of the Project or Submission (e.g., "Chest X-Ray Dataset")
  type: "project" | "submission";
  time: number;
  withWalrus?: string; // Walrus Blob ID or Explorer Link
  withSui?: string;    // Sui Transaction Digest or Link
  withSmartContract?: string; // Package ID or Link
  withLink?: string;   // Redirect URL (e.g., "/marketplace")
  buttonLabel?: string; // Custom label for the bottom link button
  storageLabel?: string;// Custom label for the storage badge
}

export function ReceiptModal({
  open,
  onOpenChange,
  header,
  description,
  itemName,
  type,
  time,
  withWalrus,
  withSui,
  withSmartContract,
  withLink,
  buttonLabel = "View Projects",
  storageLabel = "Stored on Walrus",
}: ReceiptModalProps) {

  // 1. Dynamic Icon & Label Logic
  const isProject = type === "project";
  const TypeIcon = isProject ? FolderOpen : FileText;
  const typeLabel = isProject ? "Project" : "Submission";

  // 2. Handle Download Receipt (.txt generation)
  const handleDownloadReceipt = () => {
    const lines = [
      `VANALIS - ${type.toUpperCase()} RECEIPT`,
      `========================`,
      `Status: Success`,
      `Header: ${header}`,
      `Type: ${typeLabel}`,
      `Item Name: ${itemName}`,
      `Date: ${getDateTime(time)}`,
      ``,
      `BLOCKCHAIN DETAILS`,
      `------------------`,
      withWalrus ? `Walrus Blob: ${withWalrus}` : null,
      withSui ? `Sui Transaction: ${withSui}` : null,
      withSmartContract ? `Smart Contract: ${withSmartContract}` : null,
      ``,
      `Generated by Vanalis Platform`,
    ].filter(Boolean); // Remove null lines

    const fileContent = lines.join("\n");
    const element = document.createElement("a");
    const file = new Blob([fileContent], { type: "text/plain" });
    
    element.href = URL.createObjectURL(file);
    element.download = `receipt-${type}-${Date.now()}.txt`;
    document.body.appendChild(element); // Required for this to work in FireFox
    element.click();
    document.body.removeChild(element);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-md p-0 overflow-hidden bg-white">
        
        {/* Top Section: Success Icon & Headers */}
        <div className="flex flex-col items-center pt-10 pb-6 px-6 text-center">
          <div className="h-16 w-16 bg-green-100 rounded-full flex items-center justify-center mb-4">
            <Check className="h-8 w-8 text-green-600" strokeWidth={3} />
          </div>
          <DialogTitle className="text-2xl font-bold text-gray-900">
            {header}
          </DialogTitle>
          <DialogDescription className="text-gray-500 mt-2">
            {description}
          </DialogDescription>
        </div>

        {/* Middle Section: The Receipt Card */}
        <div className="px-6 pb-6">
          <div className="bg-gray-50 border border-gray-200 rounded-xl p-5 space-y-4">
            <div className="flex items-center justify-between border-b border-gray-200 pb-2 mb-2">
              <span className="text-xs font-semibold uppercase tracking-wider text-gray-500">
                {type} Receipt
              </span>
              {withWalrus && (
                <div className="flex items-center gap-1 text-xs text-blue-600 bg-blue-50 px-2 py-0.5 rounded">
                  <Box className="h-3 w-3" />
                  {storageLabel}
                </div>
              )}
            </div>

            {/* Item Name */}
            <div className="grid grid-cols-[100px_1fr] items-start gap-2 text-sm">
              <div className="flex items-center gap-2 text-gray-500">
                <TypeIcon className="h-4 w-4" />
                <span>{typeLabel}</span>
              </div>
              <div className="text-right font-medium text-gray-900 break-words">
                {itemName}
              </div>
            </div>

            {/* Timestamp */}
            <div className="grid grid-cols-[100px_1fr] items-center gap-2 text-sm">
              <div className="flex items-center gap-2 text-gray-500">
                <Clock className="h-4 w-4" />
                <span>Time</span>
              </div>
              <div className="text-right text-gray-900">
                {getDateTime(time)}
              </div>
            </div>

            {/* Explorer Links (Conditional) */}
            <div className="space-y-3 pt-2 mt-2 border-t border-gray-200">
              {withWalrus && (
                <a 
                  href={withWalrus.startsWith('http') ? withWalrus : `https://walruscan.com/testnet/blob/${withWalrus}`} // Adjust base URL as needed
                  target="_blank" 
                  rel="noreferrer"
                  className="flex items-center justify-between text-sm text-gray-500 hover:text-blue-600 transition-colors group"
                >
                  <span className="flex items-center gap-2"># View on Walrus Explorer</span>
                  <ExternalLink className="h-4 w-4 opacity-50 group-hover:opacity-100" />
                </a>
              )}

              {withSui && (
                <a 
                  href={withSui.startsWith('http') ? withSui : `https://suiscan.xyz/testnet/tx/${withSui}`} 
                  target="_blank" 
                  rel="noreferrer"
                  className="flex items-center justify-between text-sm text-gray-500 hover:text-blue-600 transition-colors group"
                >
                  <span className="flex items-center gap-2">
                    <Database className="h-4 w-4" /> View Transaction on Sui
                  </span>
                  <ExternalLink className="h-4 w-4 opacity-50 group-hover:opacity-100" />
                </a>
              )}

              {withSmartContract && (
                <a 
                  href={withSmartContract.startsWith('http') ? withSmartContract : `https://suiscan.xyz/testnet/object/${withSmartContract}`} 
                  target="_blank" 
                  rel="noreferrer"
                  className="flex items-center justify-between text-sm text-gray-500 hover:text-blue-600 transition-colors group"
                >
                  <span className="flex items-center gap-2">
                    <FileText className="h-4 w-4" /> View Smart Contract
                  </span>
                  <ExternalLink className="h-4 w-4 opacity-50 group-hover:opacity-100" />
                </a>
              )}
            </div>
          </div>
        </div>

        {/* Bottom Section: Buttons */}
        <DialogFooter className="flex flex-col sm:flex-col gap-3 px-6 pb-8 !space-x-0">
          {/* Save Receipt Button */}
          <Button 
            className="w-full bg-green-600 hover:bg-green-700 text-white h-12 text-base font-medium shadow-sm"
            onClick={handleDownloadReceipt}
          >
            <Download className="mr-2 h-5 w-5" />
            Save Receipt
          </Button>

          {/* Optional Redirect Link */}
          {withLink && (
            <Link to={withLink} className="w-full">
              <Button 
                variant="ghost" 
                className="w-full text-gray-500 hover:text-gray-900 hover:bg-gray-100"
                onClick={() => onOpenChange(false)}
              >
                {buttonLabel}
              </Button>
            </Link>
          )}
        </DialogFooter>

      </DialogContent>
    </Dialog>
  );
}